### ISSUE TITLE
데이터 라이센스가 어떻게 되나요?

### ISSUE THREAD

**Issue by HeegyuKim** [VAIV-2023/VAIV2023#3]
안녕하세요 좋은 데이터 공개해주셔서 감사합니다.

혹시 라이센스가 어떻게 될까요?

상업적으로 이용하려는 것은 아니고, 사용하기 편하도록 RewardModel 데이터들을 huggingface dataset으로 만들어서 올려두려고 합니다.

출처는 표시하도록 하겠습니다!

**Comment by ryeowon** [comment]
안녕하세요,

데이터 오픈 여부는 12월 중 결정될 것 같습니다. 이후 라이센스를 업데이트 해두겠습니다.

감사합니다.

**Comment by ryeowon** [comment]
안녕하세요,

답변이 늦어져 죄송합니다. 데이터 오픈하는 것으로 결정되어, 저희 쪽에서 Hugging Face에 업로드하였습니다.
https://huggingface.co/datasets/Trofish/Korean-RLHF-Full-process

감사합니다.
